<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL1sXtS4\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL1sXtS4/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerL1sXtS4.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerL1sXtS4\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerL1sXtS4\appAppKernelProdContainer([
    'container.build_hash' => 'L1sXtS4',
    'container.build_id' => 'ba13c3b0',
    'container.build_time' => 1698252781,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL1sXtS4');
